const actionTypes = Object.freeze({
    INCREASE_COUNTER: 'INCREASE_COUNTER',
    DECREASE_COUNTER: 'DECREASE_COUNTER',
    // USER
    SAVE_USER_INFO_SUCCESS: 'SAVE_USER_INFO_SUCCESS',
    SAVE_USER_INFO_FAILED: 'SAVE_USER_INFO_FAILED',
    RESET_USER_INFO_SUCCESS: 'RESET_USER_INFO_SUCCESS',
    RESET_USER_INFO_FAILED: 'RESET_USER_INFO_FAILED'
});

export default actionTypes;